-- Migration: Create Kisan AI tables
-- Created: 2026-03-02

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  state TEXT NOT NULL,
  district TEXT NOT NULL,
  land_size TEXT NOT NULL,
  crops TEXT NOT NULL,
  income_category TEXT NOT NULL,
  preferred_language TEXT NOT NULL DEFAULT 'en',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- RLS Policy - Public read/write for demo
CREATE POLICY "Allow all for users" ON users FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- SCHEMES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS schemes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  state TEXT NOT NULL,
  category TEXT NOT NULL,
  eligibility TEXT NOT NULL,
  benefits TEXT NOT NULL,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE schemes ENABLE ROW LEVEL SECURITY;

-- RLS Policy - Public read
CREATE POLICY "Allow all for schemes" ON schemes FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- INTERACTIONS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  response TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;

-- RLS Policy - Public read/write for demo
CREATE POLICY "Allow all for interactions" ON interactions FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- SAMPLE DATA - Government Schemes
-- ============================================
INSERT INTO schemes (name, state, category, eligibility, benefits, link) VALUES
('PM-KISAN', 'All', 'Financial Support', 'All landholding farmer families', 'Rs. 6000 per year in 3 installments', 'https://pmkisan.gov.in'),
('Kisan Credit Card', 'All', 'Credit', 'All farmers - individual/joint borrowers', 'Easy credit up to Rs. 3 lakh at concessional rates', 'https://www.myscheme.gov.in/schemes/kcc'),
('Fasal Bima Yojana', 'All', 'Crop Insurance', 'All farmers including sharecroppers', 'Low premium 2% for Kharif, 1.5% for Rabi crops', 'https://pmfby.gov.in'),
('PMFBY - State Scheme', 'Maharashtra', 'Crop Insurance', 'Maharashtra farmers', 'Crop loss compensation up to Rs. 2 lakh', 'https://mahafbc.in'),
('RKVY-RAFTAAR', 'All', 'Agriculture Development', 'State governments and farmers', 'Funds for agriculture infrastructure and projects', 'https://rkvy.nic.in'),
('Swachh Bharat Mission - Gramin', 'All', 'Rural Development', 'Rural households', 'Toilet construction subsidy', 'https://sbm.gov.in'),
('Maharashtra Agricultural Infrastructure', 'Maharashtra', 'Infrastructure', 'Farmers and FPOs', 'Cold storage, warehouse, processing unit subsidies', 'https://mahait.org'),
('UP Kisan Samman Nidhi', 'Uttar Pradesh', 'Financial Support', 'UP farmer families', 'Additional Rs. 4000 per year to PM-KISAN beneficiaries', 'https://up.gov.in'),
('Karnataka Raitha Belaku', 'Karnataka', 'Financial Support', 'Karnataka farmers', 'Input subsidy for crops', 'https://raitamitra.karnataka.gov.in'),
('Tamil Nadu Farmers Aid', 'Tamil Nadu', 'Financial Support', 'TN farmers', 'Drought relief and input subsidies', 'https://tn.gov.in')
ON CONFLICT DO NOTHING;
